irc:
    server: irc.archivesmc.com
    port: 6667
    timeout: 120
    nick: JSONBot
    channels:
        - "#jsonbot-test"

jsonapi:
    address: localhost
    port: 20059
    username: admin
    password: demo
    salt: ''

logging:
    simple: true
    timestamps: true
    debug: false